server:
  port: 9001
spring:
  application:
    name: sharding-mysql
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test01?serverTimezone=Asia/Shanghai&useSSL=false&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
mybatis:
  mapper-locations: classpath:mapper/*.xml

